### ISSUE TITLE
Question About Unseen Labels Usage In the Training Process

### ISSUE THREAD

**Issue by GoGoDuck912** [valeoai/zero_shot_semantic_segmentation#6]
Hi @maximebucher ,

I have read your paper and code. Thank you for sharing! Here is one question,

It seems that in the implementation you [use the unseen gt labels](https://github.com/valeoai/ZS3/blob/6031f4a0be1aab15c1fcfdf930611bb93a3cf795/zs3/train_pascal_GMMN.py#L265) during the training process for finetuning.

In your setting, during the training process, the unseen labels are used, while only the unseen images are not used. Am I understanding correct?

**Comment by maximebucher** [comment]
Hi @PeikeLi ,
you are right, images with unseen classes are not used. 
The unseen gt labels are used in order to infer the statistics of appearance of each unseen classes.

Maxime

**Comment by tuanhungvu** [comment]
https://github.com/valeoai/ZS3/issues/10#issuecomment-740829384
